name: Run pi-gen
on: 
  workflow_dispatch:

jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          mkdir -p test-stage/package-test &&
          {
          cat > test-stage/package-test/00-run-chroot.sh <<EOF
          #!/bin/bash
          apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          EOF
          } &&
          chmod +x test-stage/package-test/00-run-chroot.sh &&
          echo "nodejs" > test-stage/package-test/01-packages &&
          {
          cat > test-stage/prerun.sh <<EOF
          #!/bin/bash -e
          if [ ! -d "\${ROOTFS_DIR}" ]; then
            copy_previous
          fi
          EOF
          } &&
          chmod +x test-stage/prerun.sh

      - run: |
          mkdir -p clean-stage &&
          {
          cat > clean-stage/prerun.sh <<EOF
          #!/bin/bash
          set -x
          rm -f ${{ github.workspace }}/pi-gen/stage[45]/EXPORT*
          EOF
          } &&
          chmod +x clean-stage/prerun.sh

      - uses: ./
        id: build
        with:
          image-name: test
          stage-list: clean-stage stage0 stage1 stage2 test-stage stage3 stage4 stage5
          verbose-output: true
          enable-noobs: true
          compression: xz
          compression-level: 9
          locale: de_DE.UTF-8
          hostname: pi-gen-test
          keyboard-keymap: de
          keyboard-layout: German - no dead keys
          username: pi-gen
          wpa-essid: foo
          wpa-password: '1234567890'
          timezone: Europe/London
          export-last-stage-only: false

      - run: tree 
      
      - uses: actions/upload-artifact@v4
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}
          retention-days: 2
      
      - uses: actions/upload-artifact@v4
        with:
          name: pi-gen-noobs-image
          path: ${{ steps.build.outputs.image-noobs-path }}
          retention-days: 2

